### ISSUE TITLE
think about potential "moderators"

### ISSUE THREAD

**Issue by hannesdatta** [jeroenmaagdenberg/Airbnb-curfew-impact#6]
sooo. in other words: what makes properties respond *differently to the lockdown*?

- in the city versus out of the city
- closeness to party venues
- type of houses (apartment, family house, single room)
- facilities available (like washing machine, like [...])
- extra sanitary services ("textual announcements about corona")

**Comment by jeroenmaagdenberg** [comment]
- superhost true vs false
- neighbourhood_cleansed
